### ISSUE TITLE
A bit readme for `scripts/` folder

### ISSUE THREAD

**Issue by dinhanhx** [jacksonllee/iso639#2]
I think there should be a readme for it, or at least some words about `create_languages_db.py` in `CONTRIBUTING.md`. 

https://github.com/jacksonllee/iso639/blob/main/scripts/create_languages_db.py

**Comment by jacksonllee** [comment]
Hello, thank you for the suggestion! I've just added a note about `scripts/create_languages_db.py` in `README.md` at efab0b18dfb7fd00a9a5b21c45f836170c068951. Closing this issue now.
