### ISSUE TITLE
object immutability iso639.Language

### ISSUE THREAD

**Issue by KonstZiv** [jacksonllee/iso639#3]
Objects of class iso639.Language are marked as immutable:
```python

@dataclass(frozen=True)
class Language:
    """Represents a language in the ISO 639-3 charts."""

    __slots__ = (
        # From the "codes" table
        "part3",
...
```
But when you try to use them in this way (for example, as elements of a set), you can get an error if the element other_names exists. Example:
```python
>>> import iso639
>>> cat_lng = iso639.Language.match('cat')
>>> cat_lng
Language(part3='cat', part2b='cat', part2t='cat', part1='ca', scope='I', type='L', status='A', name='Catalan', comment=None, other_names=[Name(print='Valencian', inverted='Valencian')], macrolanguage=None, retire_reason=None, retire_change_to=None, retire_remedy=None, retire_date=None)
>>> lng_set = set()
>>> lng_set.add(cat_lng)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 3, in __hash__
TypeError: unhashable type: 'list'
>>> 
```
is it possible to replace the use of a list with a tuple to describe this attribute in order to get a fully immutable object?

**Comment by jacksonllee** [comment]
Hello, thank you for catching this! I've just created a branch for a potential fix (by explicitly defining how to hash a `Language` class instance). It is available for testing if you run `pip install git+https://github.com/jacksonllee/iso639@make-language-instances-truly-hashable`. Would you be able to see if this would resolve the issue on your end?

**Comment by KonstZiv** [comment]
Hello)
Thank you for efficiency
I will be able to check within 1-2 days and I will definitely write you
about the result immediately.
Sincerely,
Konstantin

ср, 14 июн. 2023 г. в 04:45, Jackson L. Lee ***@***.***>:

**Comment by KonstZiv** [comment]
Hello!
Today I was able to check the work of the updated package - everything is
ok, thanks!
As far as I understand, you tied the hash to part3, as the most complete.
Hope this works for me too.
When can we expect an update in pypi?
I will now have some work with languages, I`ll use your package, if there
are any difficulties, I will definitely write.
Thanks for the quick response
Best regards, Konstantin

ср, 14 июн. 2023 г. в 17:28, Konstantin Zivenko ***@***.***>:

**Comment by jacksonllee** [comment]
Thank you for confirming that the fix would work for you! I've just made a new release to PyPI, version `2023.6.15`, so running `pip install --upgrade python-iso639` should get you this latest version.

Closing this issue now -- thank you again for catching and reporting this issue!
